version: "3.8"
services:
  db:
    build: ./database/
    networks:
        - course_reg_nw
  user-service:
    build: ./app/
    ports:
        - "8080:8080"
    networks:
        - course_reg_nw
    depends_on:
        - db
networks:
   course_reg_nw:
    name: course_reg_nw
    external: true