# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.31.1
        command: ["./wait-for-it.sh", "db-service:5432", "--timeout=60", "--"]
      containers:
      - name: app
        image: vanidevilekkala/scalable-services:userservice-app-v1
        ports:
        - containerPort: 8080  # Replace with the port your app service is listening on
      # Add an init container to wait for the database to be ready
      initContainers:
      - name: wait-for-db
        image: busybox:1.31.1
        command: ['sh', '-c', 'until nslookup db-service; do echo waiting for db-service; sleep 2; done;']

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: vanidevilekkala/scalable-services:userservice-db-v1

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
